# Generated by Django 2.2.15 on 2021-01-14 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, verbose_name='ФИО')),
                ('slug', models.SlugField(default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+700112299'. Макс. длинна = 16 знаков", regex='^\\+?1?\\d{9,16}$')], verbose_name='Телефон')),
                ('type', models.CharField(blank=True, choices=[('Физ лицо', 'Физ лицо'), ('Юр лицо', 'Юр лицо'), ('Компания', 'Компания'), ('ОАО', 'ОАО'), ('ОсОО', 'ОсОО'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ЗАО', 'ЗАО'), ('НКО', 'НКО'), ('НПО', 'НПО'), ('Фонд', 'Фонд'), ('Банк', 'Банк'), ('Отсутствует', 'Отсутствует')], default=('Отсутствует', 'Отсутствует'), max_length=16, verbose_name='Тип')),
                ('origin', models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Соцсети', 'Соцсети'), ('Сарафанное радио', 'Сарафанное радио'), ('E-mail рассылка', 'E-mail рассылка'), ('Отсутствует', 'Отсутствует')], default=('Отсутствует', 'Отсутствует'), max_length=16, verbose_name='Источник')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'db_table': 'client',
                'ordering': ['name'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
